---
title: "Salary Analysis"
author: "Ashen Shavinda"
date: "1/14/2022"
output:
  word_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
```



```{r}
Salary <- read.csv("salary.csv")
View(Salary)
```

```{r}
toalNum <- Salary %>% summarise(count=n())
toalNum
```

```{r}
summary(Salary)
```

```{r}
avg_1 <- Salary %>% summarise(avg_salary=mean(salary))
avg_1

```

```{r}
avg_2 <- Salary %>% group_by(education) %>% summarise(avg_salary=mean(salary))
avg_2
```

```{r}
box_plot <- ggplot(Salary, aes(x = education, y = salary))
box_plot + geom_boxplot()
```

```{r}
pers <- Salary %>% select(health,health_ins) %>% filter(health == "Good" & health_ins == "Yes") %>% summarise(percentage = 100*n()/nrow(Salary)) 
pers
```

```{r}
counts <- table(Salary$maritl, Salary$jobclass)
barplot(counts, main="Job classes across the different Martial status",
        xlab="Job Class",ylab="Martial Status", col=c("darkblue","Gray","Orange","Yellow","Green"),
        legend = rownames(counts), beside=TRUE)
```












